version: '3.1'

services:
  distribuidoraDB:
    image: postgres:15.3
    container_name: distribuidoraDB
    restart: always
    environment:
      POSTGRES_DB: distribuidoraDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
